# Generated by Django 2.1.2 on 2018-11-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DroneLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='FALSE', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='InterPlaceDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=100)),
                ('imageUrl', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airsupply.Category')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airsupply.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('None', 'None')], max_length=100)),
                ('status', models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cart', 'Cart')], max_length=100)),
                ('totalWeight', models.DecimalField(decimal_places=2, max_digits=100)),
                ('timeOrdered', models.DateTimeField(blank=True, null=True)),
                ('timeDelivered', models.DateTimeField(blank=True, null=True)),
                ('timeDispatched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('altitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='airsupply.Order')),
            ],
            bases=('airsupply.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='clinicManager',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='airsupply.ClinicManager'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='airsupply.LineItem'),
        ),
        migrations.AddField(
            model_name='interplacedistance',
            name='fromLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='airsupply.Place'),
        ),
        migrations.AddField(
            model_name='interplacedistance',
            name='toLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='airsupply.Place'),
        ),
        migrations.AddField(
            model_name='droneload',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='airsupply.Order'),
        ),
        migrations.AddField(
            model_name='clinicmanager',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airsupply.Place'),
        ),
        migrations.AddField(
            model_name='clinicmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interplacedistance',
            unique_together={('fromLocation', 'toLocation')},
        ),
    ]
