# Generated by Django 2.1.2 on 2018-11-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airsupply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched', models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=5)),
                ('orders', models.ManyToManyField(blank=True, null=True, to='airsupply.Order')),
            ],
        ),
        migrations.CreateModel(
            name='InterPlaceDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fromLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='airsupply.Place')),
                ('toLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='airsupply.Place')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interplacedistance',
            unique_together={('fromLocation', 'toLocation')},
        ),
    ]
