# Generated by Django 2.1.2 on 2018-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airsupply', '0002_auto_20181107_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('priority', 'timeOrdered')},
        ),
        migrations.AlterField(
            model_name='droneload',
            name='dispatched',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='FALSE', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Queued for Processing', 'Queued for Processing'), ('Processing by Warehouse', 'Processing by Warehouse'), ('Queued for Dispatch', 'Queued for Dispatch'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cart', 'Cart')], max_length=100),
        ),
    ]
