# Generated by Django 2.1.2 on 2018-11-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airsupply', '0003_auto_20181112_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
